[buildpack]
name = "Ruby"
ruby_version = "2.5.6"

  [publish.Ignore]
  files = [
    "spec/"
  ]

  [[publish.Vendor]]
  url = "https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/ruby.tgz"
  dir = "."
  files = ["./.env"]
